#!/bin/sh
#
# Convert cyrillyc files names to translit

TR="
s/А/A/g;
s/а/a/g;
s/Б/B/g;
s/б/b/g;
s/в/v/g;
s/В/V/g;
s/г/g/g;
s/Г/G/g;
s/д/d/g;
s/Д/D/g;
s/е/e/g;
s/Е/e/g;
s/ё/yo/g;
s/Ё/Yo/g;
s/ж/zh/g;
s/Ж/Zh/g;
s/з/z/g;
s/З/Z/g;
s/и/i/g;
s/И/I/g;
s/й/j/g;
s/Й/J/g;
s/к/k/g;
s/К/K/g;
s/л/l/g;
s/Л/L/g;
s/м/m/g;
s/М/M/g;
s/н/n/g;
s/Н/N/g;
s/о/o/g;
s/О/O/g;
s/п/p/g;
s/П/P/g;
s/р/r/g;
s/Р/R/g;
s/с/s/g;
s/С/S/g;
s/т/t/g;
s/Т/T/g;
s/у/u/g;
s/У/U/g;
s/ф/f/g;
s/Ф/F/g;
s/х/h/g;
s/Х/H/g;
s/ц/c/g;
s/Ц/C/g;
s/ч/ch/g;
s/Ч/Ch/g;
s/ш/sh/g;
s/Ш/Sh/g;
s/щ/sch/g;
s/Щ/Sch/g;
s/э/e/g;
s/Э/E/g;
s/ю/ju/g;
s/Ю/Ju/g;
s/я/ya/g;
s/Я/Ya/g;
s/ъ//g;
s/Ъ//g;
s/ь//g;
s/Ь//g;
s/ы/y/g;
s/Ы/Y/g;
"

for i in "$@"; do
    NEW=$(echo -n $i | sed -e "$TR")
    echo "$i → $NEW"
    mv "$i" "$NEW"
done
