#!/usr/bin/python
"""
Simple program for initializing cabal projects
"""

# optparse is deprecated but I stick woth it since argparse is only
# available since 2.7
import optparse

# ================================================================
# Templates
# ================================================================

# ----------------------------------------
template_lib = """
Name:           ${name}
Version:        0.1
Synopsis:       <<<SYNOPSIS>>>
Description:
  <<<DESCRIPTION>>>

Cabal-Version:  >= 1.10
License:        BSD3
License-File:   LICENSE
Author:         Aleksey Khudyakov <alexey.skladnoy@gmail.com>
Maintainer:     Aleksey Khudyakov <alexey.skladnoy@gmail.com>
Homepage:       http://bitbucket.org/Shimuuar/${name}
Category:       Data
Build-Type:     Simple

source-repository head
  type:     hg
  location: http://bitbucket.org/Shimuuar/${name}

Library
  Ghc-options:          -Wall
  Default-Language:    Haskell2010
  Build-Depends:
    base >=3 && <5
  Exposed-modules:
"""

# ----------------------------------------
template_inr_lib = """
Name:           ${name}
Version:        0.1
Synopsis:       <<<SYNOPSIS>>>
Description:
  <<<DESCRIPTION>>>

Cabal-Version:  >= 1.10
License:        BSD3
License-File:   LICENSE
Author:         Aleksey Khudyakov <alexey.skladnoy@gmail.com>
Maintainer:     Aleksey Khudyakov <alexey.skladnoy@gmail.com>
Category:       HEP
Build-Type:     Simple

Library
  Ghc-options:          -Wall
  Default-Language:    Haskell2010
  Build-Depends:
    base >=3 && <5
  Exposed-modules:
"""

# ----------------------------------------
template_inr_exe = """
Name:           ${name}
Version:        0.1
Synopsis:       <<<SYNOPSIS>>>
Description:
  <<<DESCRIPTION>>>

Cabal-Version:  >= 1.10
License:        BSD3
License-File:   LICENSE
Author:         Aleksey Khudyakov <alexey.skladnoy@gmail.com>
Maintainer:     Aleksey Khudyakov <alexey.skladnoy@gmail.com>
Category:       HEP
Build-Type:     Simple

Library
  Ghc-options:          -Wall
  Default-Language:    Haskell2010
  Build-Depends:
    base >=3 && <5
  Exposed-modules:
"""


# ----------------------------------------
template_setup = """
import Distribution.Simple
main = defaultMain
"""

# ================================================================
# Main
# ================================================================

parser = optparse.OptionParser()
parser.add_option("--inr")
