#!/bin/bash
## This script is used to bootstrap cabal

TMP=$(mktemp -d);

function fail() { echo "$1" >&2; rm -rf "$TMP"; exit 1; }

function gettar() {
    cd $(wget -q "$1" -O - | tar xzvf - | (head -1 ; cat > /dev/null))
}

function build() {
    ghc --make Setup
    ./Setup configure --user          || fail 'Configure step failed'
    ./Setup build                     || fail 'Build step failed'
}

function register() { ./Setup register --user --inplace || fail 'register step failed'; }


cd "$TMP";
# Get zlib
gettar http://hackage.haskell.org/packages/archive/zlib/0.5.0.0/zlib-0.5.0.0.tar.gz
build
register
# Get HTTP
gettar http://hackage.haskell.org/packages/archive/HTTP/3001.1.4/HTTP-3001.1.4.tar.gz
build
register
# Get cabal
gettar http://hackage.haskell.org/packages/archive/Cabal/1.6.0.1/Cabal-1.6.0.1.tar.gz
build
register
# Get cabal install itself
gettar http://hackage.haskell.org/packages/archive/cabal-install/0.6.0/cabal-install-0.6.0.tar.gz
build

# Unregister unneeded libraries 
ghc-pkg unregister --user zlib
ghc-pkg unregister --user HTTP
ghc-pkg unregister --user Cabal
# Now use cabal-install to install itself and its dependencies
./dist/build/cabal/cabal update
./dist/build/cabal/cabal install cabal-install

# Clean up
rm -rf "$TMP";
