#!/bin/sh
 
# less-like functionality with dzen.

# Parse command line arguments
SCROLL=scrollhome
while getopts "be" flag; do
    [ $flag = e ] && SCROLL=scrollend
    [ $flag = b ] && SCROLL=scrollhome
done

dzen2 -l 30 -p -y 54 \
    -e "onstart=uncollapse,$SCROLL;button3=exit;button4=scrollup;button5=scrolldown;"
