#!/bin/sh

# Number of konquerors running.
NKONQ= $(dcop | grep konqueror -c)

if [ $NKONQ == '0' ] ; then
    # Create new broser instance 
    konqueror $1
elif [ $NCONQ == '1' ]; then
    # Open link in new tab 
    dcop $(dcop | grep konqueror) konqueror-mainwindow#1 newTab $1
else
    # More than one konqueror opened. Fail as we cannot choose
    "More than one konqueror opened" >&2
    exit 1
fi

