#!/bin/sh

function fail() { echo $@ >&2; exit 1; }

# Chec
[ $(sselp | wc -l) = '1'   ] || fail "look_dictionary: Multiline selection"
[ $(sselp | wc -m) -lt 128 ] || fail "look_dictionary: Too long selection"

# Print result to stdout
sselp
dict $(sselp) 2>&1
