#!/bin/sh

LOOKUP=$(sselp)

(echo "$LOOKUP"; echo; dict "$LOOKUP" 2>&1 ) |
dzen2 -l 30 -p -y 37 $DZEN_COLOR $DZEN_FONT \
    -e 'onstart=uncollapse,scrollhome;button1=exit;button4=scrollup;button5=scrolldown;'
