#!/usr/bin/python
"""
Waits for network manager to connect.
"""

from sys  import argv, exit, stderr
from time import sleep
import dbus
             
NM_STATE_UNKNOWN = 0
NM_STATE_ASLEEP = 1
NM_STATE_CONNECTING = 2
NM_STATE_CONNECTED = 3
NM_STATE_DISCONNECTED = 4

def usage() :
    print>>stderr, "Waits for network-manager to connect to network or exits on timeout with\nnon-zero exit code."
    print>>stderr, "Usage:\n    ntm-wait [timeout]"
    exit(1)

def wait4nm(timeout) :
    "Wait for network manager timeout."
    bus = dbus.SystemBus()
    nm = bus.get_object('org.freedesktop.NetworkManager', '/org/freedesktop/NetworkManager')
    while timeout > 0 :
        if nm.state() == NM_STATE_CONNECTED : return True
        timeout -= 1
    return False

try :
    timeout = 120
    if len(argv) > 1 :
        timeout = int(argv[1])
    if not wait4nm(timeout) :
        exit(1)
except ValueError :
    usage()

