#!/bin/sh

(echo MPC playlist; mpc playlist) | 
dzen2 -l 30 -p -y 37 \
    -e 'onstart=uncollapse,scrollhome,grabkeys;'\
'button1=exit;button4=scrollup;button5=scrolldown;'\
'key_Page_Down=scrolldown:8;key_Page_Up=scrollup:8;key_q=exit'
