#!/usr/bin/perl

use warnings;
use strict;
use Getopt::Std;

# Parse command line
my %opt;
getopt(':p', \%opt);
my $prepend = $opt{'p'} ? $opt{'p'} : '';

# Extract URLs
print "@ARGV\n";
while( <> ) {
    while( /<[aA] [^>]*href=["']?([^"' <>]*)["']?[^>]*>/g ) {
	print "$prepend$1\n";
    }
}
