#!/bin/sh

fail() { echo "$@" >&2; exit 1; }

# Create temporary fifo
TEMP=$(mktemp -q -d) || fail "Cannot create FIFO"
FIFO="$TEMP/fifo" 
mkfifo "$FIFO" || (rm -rf "$TEMP"; fail "Cannot create FIFO") 

if ! tty -s ; then 
    xterm -geom 120x40 -name 'terminal-float' -e sh -c "cat '$FIFO' | less" &
    cat > "$FIFO" 
fi

# Clean up FIFO
rm -rf "$TEMP"
