#!/bin/sh

DATE_CNT=0
MEM_CNT=0

while : ; do
    # mpd song name
    MPD_STR=$(mpc --format '%artist% - %title%' | xbar_mpd)

    # Date 
    if [ $DATE_CNT = 0 ]; then
        DATE_CNT=60
        DATE_STR=$(date '+%H:%M [%d %b %Y]')
    fi
    DATE_CNT=$((DATE_CNT-1))

    # Memory usage
    if [ $MEM_CNT = 0 ]; then
        MEM_CNT=10
        MEM_STR=$(xbar_mem /proc/meminfo)
    fi
    MEM_CNT=$((MEM_CNT-1))
    
    echo "$MPD_STR | $MEM_STR | $DATE_STR"
    sleep 1  
done
