#!/bin/bash

X=${1-0}
Y=${2-0}
WID=${3-400}

TODAY=$(date +'%_d')
MONTH=$(date +'%_m')
YEAR=$(date  +'%Y')

function cal_highlight()
{
    sed -e '1 s/.*/^fg(white)&^fg()/'
}

(
    # Current date 
    date '+^fg(white)^bg(darkgrey)%H:%M [%A %d %B %Y]^fg()^bg()'

    # Prev month
    [ $MONTH -eq 1 ] && YR=$((YEAR - 1)) || YR=$YEAR
    [ $MONTH -eq 1 ] && MON=12           || MON=$((MONTH-1))
    cal $MON $YR | cal_highlight
    
    # Current month
    cal | cal_highlight | sed -e "s/$TODAY/^bg(white)^fg(black)&^fg()^bg()/"

    # Next month 
    [ $MONTH -eq 12 ] && YR=$((YEAR + 1)) || YR=$YEAR
    [ $MONTH -eq 12 ] && MON=1            || MON=$((MONTH+1))
    cal $MON $YR | cal_highlight
) | dzen2 -p -l 24 -ta c -sa c -x $X -y $Y -w $WID \
    -e 'onstart=uncollapse;button3=exit'