#!/bin/sh

# Copied from http://braindump.dk/tech/category/xmonad/
# and modified by me.


AWKS='
BEGIN {
    WIDTH  = 40;
    HEIGHT = 10;
    FG = "white";
    BG = "darkgrey";
    MG = "#fea";
}

/^MemTotal/  {t=$2}; 
/^MemFree/   {f=$2}; 
/^Buffers/   {b=$2};
/^Cached/    {c=$2};
/^SwapTotal/ {st=$2}; 
/^SwapFree/  {sf=$2}; 

function print_rect(color, width) {
    printf("^fg(%s)^r(%dx%d)", color, width, HEIGHT)
}

END {
    printf("Mem:");
    print_rect(FG,    WIDTH*(t-b-c-f)/t);
    print_rect(MG,     WIDTH*(b+c)/t);
    print_rect(BG, WIDTH*f/t);

    print_rect("black", 4);

    print_rect(FG, WIDTH*(st-sf)/st);
    print_rect(BG, WIDTH*sf/st);
    printf("\n");
}'

while : ; do
    awk "$AWKS" /proc/meminfo
    sleep 5
done
