#!/usr/bin/awk -f

# Copied from http://braindump.dk/tech/category/xmonad/
# and modified by me.

BEGIN { 
  BG="#666"; 
  FG="#fea"; 
  MG="#f44";
  WIDTH=30; 
  HEIGHT=10; 
}
 
/^MemTotal/  {t=$2}; 
/^MemFree/   {f=$2}; 
/^Buffers/   {b=$2};
/^Cached/    {c=$2};
/^SwapTotal/ {st=$2}; 
/^SwapFree/  {sf=$2}; 

function print_rect(color, width) {
    printf("^fg(%s)^r(%dx%d)", color, width, HEIGHT)
}

END { 
    # Width of cache/buffers bar   
    cw=int(WIDTH*(c+b)/t);
    # Width used memory bar 
    mw=int(WIDTH*(t-f-c-b)/t); 

    # Width of swap bar 
    sw=int(WIDTH*(st-sf)/st); 
 
    printf("Mem: ^ib(1)");
    print_rect(BG, mw);
    print_rect(FG, cw);
    print_rect(MG, WIDTH-mw-cw);

    print_rect("black", 4);

    print_rect(FG, sw);
    print_rect(BG, WIDTH-sw);
    printf("^ib(0)^fg()\n");
}
