#!/bin/sh

## ================================================================
## Set up X.org
## ================================================================
# Set xkb options
setxkbmap -model pc104 -layout us,ru -variant basic,winkeys 
setxkbmap -option -option "grp_led:scroll,grp:shifts_toggle,compose:menu,ctrl:nocaps" 

[ -f ~/.Xresources ] && xrdb ~/.Xresources # Read resources
[ -f ~/.Xmodmap    ] && xmodmap ~/.Xmodmap # read modmaps

# Cleanup resources
rm -rf .macromedia/*

## ================================================================
## Set input methods
## ================================================================
export GTK_IM_MODULE=xim
# if which scim; then
#     export XMODIFIERS='@im=scim-bridge'
#     export GTK_IM_MODULE="scim-bridge"
#     export QT_IM_MODULE="scim-bridge"
#     scim -d
# fi

## ================================================================
## Run session programs
## ================================================================
killall gpg-agent
eval $(gpg-agent --daemon)
which mpdscribble && mpdscribble --conf ~/.mpdscribble/mpdscribble
which conky       && conky
which tint2       && tint2 -c ~/.config/tint2/tint2rc

## ================================================================
## Wallpaper
## ================================================================
[ -f ~/.wallpaper ] && feh --bg-center ~/.wallpaper


## ================================================================
## Run window manager
## ================================================================
xmonad &
XMONAD_PID=$!


## ================================================================
## Autorun
## ================================================================
AUTORUN=~/.config/autorun
[ -f $AUTORUN ] && sh $AUTORUN &


## ================================================================
## Cleanup
## ================================================================
wait $XMONAD_PID		# wait for xmonad termination
pkill -HUP -P $$		# send SIGHUP to all children
mpc pause			# Stop music
wait				# Wait for everyone to terminate

