#!/bin/sh

# Read resources
xrdb ~/.Xresources

# Create pipe for xmonad
PIPE=~/.share/xmonad-pipe
rm -f $PIPE
mkfifo -m 600 $PIPE
[ -p $PIPE ] || exit

## Download wallpaper from APOD
xsetroot -solid black
apod_get_wallpaper.sh &

## Launch kdeinit
kdeinit 

## Run bars
export DZEN_COLOR='-fg #8f8 -bg #000'
export DZEN_FONT='-fn -xos4-terminus-medium-r-normal-*-16-160-*-*-*-*-iso10646-*'
# Main bar 
xbar | dzen2 $DZEN_COLOR $DZEN_FONT -ta r  -w 880  -x 126 &
# System tray
stalonetray -bg '#000' --icon-size 18 --geometry 144x18+0+0 &
# WM state bar 
dzen2 $DZEN_COLOR $DZEN_FONT -ta c -y 18 < $PIPE &

## Autorun
AUTORUN=~/.etc/autorun
[ -f $AUTORUN ] && sleep 3 ; source $AUTORUN

# Run window manager 
/usr/bin/xmonad > $PIPE 

# Cleanup

# send SIGHUP to all children
pkill -HUP -P $$ 
# Wait for everyone to terminate
wait
