#!/bin/sh

# Read resources
xrdb ~/.Xresources

# Create pipe for xmonad
PIPE=~/.share/xmonad-pipe
rm -f $PIPE
mkfifo -m 600 $PIPE
[ -p $PIPE ] || exit

## Download wallpaper from APOD
xsetroot -solid black
apod_get_wallpaper.sh &

## Launch kdeinit
kdeinit 

## Run bars
# System tray
stalonetray -bg '#000' --icon-size 18 --geometry 144x18+0+0 -e ''&
# MPD status bar
xbar_mpd | dzen2 -ta l -w 566 -x 144 -e '' &
# Memory meter
xbar_mem | dzen2 -w 144 -x 710 -e '' &
# dzen clock
dzen_clock | dzen2 -x $((1024-170)) -w 170 \
    -e 'button1=exec:dzen_cal 760 0 264' &
# WM state bar 
dzen2 $DZEN_COLOR $DZEN_FONT -ta c -y 18 -e '' < $PIPE &

## Autorun
AUTORUN=~/.etc/autorun
[ -f $AUTORUN ] && sleep 3 ; source $AUTORUN

# Run window manager 
/usr/bin/xmonad > $PIPE 


## Cleanup
# send SIGHUP to all children
pkill -HUP -P $$ 
# Wait for everyone to terminate
wait
